//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace Project3.svcMLS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MLS_APISoap", Namespace="http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class MLS_API : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback searchHomesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getHomeOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteHomeOperationCompleted;
        
        private System.Threading.SendOrPostCallback modifyHomeOperationCompleted;
        
        private System.Threading.SendOrPostCallback createHomeOperationCompleted;
        
        private System.Threading.SendOrPostCallback createViewingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteViewingOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRealtorsOperationCompleted;
        
        private System.Threading.SendOrPostCallback showListingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getClientsOperationCompleted;
        
        private System.Threading.SendOrPostCallback createClientOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MLS_API() {
            this.Url = global::Project3.Properties.Settings.Default.Project3_svcMLS_MLS_API;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event searchHomesCompletedEventHandler searchHomesCompleted;
        
        /// <remarks/>
        public event getHomeCompletedEventHandler getHomeCompleted;
        
        /// <remarks/>
        public event deleteHomeCompletedEventHandler deleteHomeCompleted;
        
        /// <remarks/>
        public event modifyHomeCompletedEventHandler modifyHomeCompleted;
        
        /// <remarks/>
        public event createHomeCompletedEventHandler createHomeCompleted;
        
        /// <remarks/>
        public event createViewingsCompletedEventHandler createViewingsCompleted;
        
        /// <remarks/>
        public event deleteViewingCompletedEventHandler deleteViewingCompleted;
        
        /// <remarks/>
        public event getRealtorsCompletedEventHandler getRealtorsCompleted;
        
        /// <remarks/>
        public event showListingsCompletedEventHandler showListingsCompleted;
        
        /// <remarks/>
        public event getClientsCompletedEventHandler getClientsCompleted;
        
        /// <remarks/>
        public event createClientCompletedEventHandler createClientCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/searchHomes", RequestNamespace="http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/", ResponseNamespace="http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet searchHomes(string address, string city, string state, float maxPrice, int sqft, string availability, int bedrooms, float bathrooms, string type) {
            object[] results = this.Invoke("searchHomes", new object[] {
                        address,
                        city,
                        state,
                        maxPrice,
                        sqft,
                        availability,
                        bedrooms,
                        bathrooms,
                        type});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void searchHomesAsync(string address, string city, string state, float maxPrice, int sqft, string availability, int bedrooms, float bathrooms, string type) {
            this.searchHomesAsync(address, city, state, maxPrice, sqft, availability, bedrooms, bathrooms, type, null);
        }
        
        /// <remarks/>
        public void searchHomesAsync(string address, string city, string state, float maxPrice, int sqft, string availability, int bedrooms, float bathrooms, string type, object userState) {
            if ((this.searchHomesOperationCompleted == null)) {
                this.searchHomesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsearchHomesOperationCompleted);
            }
            this.InvokeAsync("searchHomes", new object[] {
                        address,
                        city,
                        state,
                        maxPrice,
                        sqft,
                        availability,
                        bedrooms,
                        bathrooms,
                        type}, this.searchHomesOperationCompleted, userState);
        }
        
        private void OnsearchHomesOperationCompleted(object arg) {
            if ((this.searchHomesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.searchHomesCompleted(this, new searchHomesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/getHome", RequestNamespace="http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/", ResponseNamespace="http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getHome(int homeID) {
            object[] results = this.Invoke("getHome", new object[] {
                        homeID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getHomeAsync(int homeID) {
            this.getHomeAsync(homeID, null);
        }
        
        /// <remarks/>
        public void getHomeAsync(int homeID, object userState) {
            if ((this.getHomeOperationCompleted == null)) {
                this.getHomeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetHomeOperationCompleted);
            }
            this.InvokeAsync("getHome", new object[] {
                        homeID}, this.getHomeOperationCompleted, userState);
        }
        
        private void OngetHomeOperationCompleted(object arg) {
            if ((this.getHomeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getHomeCompleted(this, new getHomeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/deleteHome", RequestNamespace="http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/", ResponseNamespace="http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int deleteHome(int homeID) {
            object[] results = this.Invoke("deleteHome", new object[] {
                        homeID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void deleteHomeAsync(int homeID) {
            this.deleteHomeAsync(homeID, null);
        }
        
        /// <remarks/>
        public void deleteHomeAsync(int homeID, object userState) {
            if ((this.deleteHomeOperationCompleted == null)) {
                this.deleteHomeOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteHomeOperationCompleted);
            }
            this.InvokeAsync("deleteHome", new object[] {
                        homeID}, this.deleteHomeOperationCompleted, userState);
        }
        
        private void OndeleteHomeOperationCompleted(object arg) {
            if ((this.deleteHomeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteHomeCompleted(this, new deleteHomeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/modifyHome", RequestNamespace="http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/", ResponseNamespace="http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int modifyHome(string address, string city, string state, float listPrice, int sqft, string availability, int bedrooms, double bathrooms, string type, int realtorID, int homeID) {
            object[] results = this.Invoke("modifyHome", new object[] {
                        address,
                        city,
                        state,
                        listPrice,
                        sqft,
                        availability,
                        bedrooms,
                        bathrooms,
                        type,
                        realtorID,
                        homeID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void modifyHomeAsync(string address, string city, string state, float listPrice, int sqft, string availability, int bedrooms, double bathrooms, string type, int realtorID, int homeID) {
            this.modifyHomeAsync(address, city, state, listPrice, sqft, availability, bedrooms, bathrooms, type, realtorID, homeID, null);
        }
        
        /// <remarks/>
        public void modifyHomeAsync(string address, string city, string state, float listPrice, int sqft, string availability, int bedrooms, double bathrooms, string type, int realtorID, int homeID, object userState) {
            if ((this.modifyHomeOperationCompleted == null)) {
                this.modifyHomeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmodifyHomeOperationCompleted);
            }
            this.InvokeAsync("modifyHome", new object[] {
                        address,
                        city,
                        state,
                        listPrice,
                        sqft,
                        availability,
                        bedrooms,
                        bathrooms,
                        type,
                        realtorID,
                        homeID}, this.modifyHomeOperationCompleted, userState);
        }
        
        private void OnmodifyHomeOperationCompleted(object arg) {
            if ((this.modifyHomeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.modifyHomeCompleted(this, new modifyHomeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/createHome", RequestNamespace="http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/", ResponseNamespace="http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int createHome(string address, string city, string state, float listPrice, int sqft, string availability, int bedrooms, double bathrooms, string type, int realtorID) {
            object[] results = this.Invoke("createHome", new object[] {
                        address,
                        city,
                        state,
                        listPrice,
                        sqft,
                        availability,
                        bedrooms,
                        bathrooms,
                        type,
                        realtorID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void createHomeAsync(string address, string city, string state, float listPrice, int sqft, string availability, int bedrooms, double bathrooms, string type, int realtorID) {
            this.createHomeAsync(address, city, state, listPrice, sqft, availability, bedrooms, bathrooms, type, realtorID, null);
        }
        
        /// <remarks/>
        public void createHomeAsync(string address, string city, string state, float listPrice, int sqft, string availability, int bedrooms, double bathrooms, string type, int realtorID, object userState) {
            if ((this.createHomeOperationCompleted == null)) {
                this.createHomeOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateHomeOperationCompleted);
            }
            this.InvokeAsync("createHome", new object[] {
                        address,
                        city,
                        state,
                        listPrice,
                        sqft,
                        availability,
                        bedrooms,
                        bathrooms,
                        type,
                        realtorID}, this.createHomeOperationCompleted, userState);
        }
        
        private void OncreateHomeOperationCompleted(object arg) {
            if ((this.createHomeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createHomeCompleted(this, new createHomeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/createViewings", RequestNamespace="http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/", ResponseNamespace="http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool createViewings(object[] homesAndDates, int clientID) {
            object[] results = this.Invoke("createViewings", new object[] {
                        homesAndDates,
                        clientID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void createViewingsAsync(object[] homesAndDates, int clientID) {
            this.createViewingsAsync(homesAndDates, clientID, null);
        }
        
        /// <remarks/>
        public void createViewingsAsync(object[] homesAndDates, int clientID, object userState) {
            if ((this.createViewingsOperationCompleted == null)) {
                this.createViewingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateViewingsOperationCompleted);
            }
            this.InvokeAsync("createViewings", new object[] {
                        homesAndDates,
                        clientID}, this.createViewingsOperationCompleted, userState);
        }
        
        private void OncreateViewingsOperationCompleted(object arg) {
            if ((this.createViewingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createViewingsCompleted(this, new createViewingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/deleteViewing", RequestNamespace="http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/", ResponseNamespace="http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int deleteViewing(int hsrID) {
            object[] results = this.Invoke("deleteViewing", new object[] {
                        hsrID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void deleteViewingAsync(int hsrID) {
            this.deleteViewingAsync(hsrID, null);
        }
        
        /// <remarks/>
        public void deleteViewingAsync(int hsrID, object userState) {
            if ((this.deleteViewingOperationCompleted == null)) {
                this.deleteViewingOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteViewingOperationCompleted);
            }
            this.InvokeAsync("deleteViewing", new object[] {
                        hsrID}, this.deleteViewingOperationCompleted, userState);
        }
        
        private void OndeleteViewingOperationCompleted(object arg) {
            if ((this.deleteViewingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteViewingCompleted(this, new deleteViewingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/getRealtors", RequestNamespace="http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/", ResponseNamespace="http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getRealtors() {
            object[] results = this.Invoke("getRealtors", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getRealtorsAsync() {
            this.getRealtorsAsync(null);
        }
        
        /// <remarks/>
        public void getRealtorsAsync(object userState) {
            if ((this.getRealtorsOperationCompleted == null)) {
                this.getRealtorsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRealtorsOperationCompleted);
            }
            this.InvokeAsync("getRealtors", new object[0], this.getRealtorsOperationCompleted, userState);
        }
        
        private void OngetRealtorsOperationCompleted(object arg) {
            if ((this.getRealtorsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRealtorsCompleted(this, new getRealtorsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/showListings", RequestNamespace="http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/", ResponseNamespace="http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet showListings(int realtorID) {
            object[] results = this.Invoke("showListings", new object[] {
                        realtorID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void showListingsAsync(int realtorID) {
            this.showListingsAsync(realtorID, null);
        }
        
        /// <remarks/>
        public void showListingsAsync(int realtorID, object userState) {
            if ((this.showListingsOperationCompleted == null)) {
                this.showListingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnshowListingsOperationCompleted);
            }
            this.InvokeAsync("showListings", new object[] {
                        realtorID}, this.showListingsOperationCompleted, userState);
        }
        
        private void OnshowListingsOperationCompleted(object arg) {
            if ((this.showListingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.showListingsCompleted(this, new showListingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/getClients", RequestNamespace="http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/", ResponseNamespace="http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getClients() {
            object[] results = this.Invoke("getClients", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getClientsAsync() {
            this.getClientsAsync(null);
        }
        
        /// <remarks/>
        public void getClientsAsync(object userState) {
            if ((this.getClientsOperationCompleted == null)) {
                this.getClientsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetClientsOperationCompleted);
            }
            this.InvokeAsync("getClients", new object[0], this.getClientsOperationCompleted, userState);
        }
        
        private void OngetClientsOperationCompleted(object arg) {
            if ((this.getClientsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getClientsCompleted(this, new getClientsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/createClient", RequestNamespace="http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/", ResponseNamespace="http://cis-iis2.temple.edu/Fall2014/cis3342_tuf01657/Project3WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int createClient(string name, string phone) {
            object[] results = this.Invoke("createClient", new object[] {
                        name,
                        phone});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void createClientAsync(string name, string phone) {
            this.createClientAsync(name, phone, null);
        }
        
        /// <remarks/>
        public void createClientAsync(string name, string phone, object userState) {
            if ((this.createClientOperationCompleted == null)) {
                this.createClientOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateClientOperationCompleted);
            }
            this.InvokeAsync("createClient", new object[] {
                        name,
                        phone}, this.createClientOperationCompleted, userState);
        }
        
        private void OncreateClientOperationCompleted(object arg) {
            if ((this.createClientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createClientCompleted(this, new createClientCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void searchHomesCompletedEventHandler(object sender, searchHomesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class searchHomesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal searchHomesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getHomeCompletedEventHandler(object sender, getHomeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getHomeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getHomeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void deleteHomeCompletedEventHandler(object sender, deleteHomeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteHomeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteHomeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void modifyHomeCompletedEventHandler(object sender, modifyHomeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class modifyHomeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal modifyHomeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void createHomeCompletedEventHandler(object sender, createHomeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createHomeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createHomeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void createViewingsCompletedEventHandler(object sender, createViewingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createViewingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createViewingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void deleteViewingCompletedEventHandler(object sender, deleteViewingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteViewingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteViewingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getRealtorsCompletedEventHandler(object sender, getRealtorsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRealtorsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRealtorsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void showListingsCompletedEventHandler(object sender, showListingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class showListingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal showListingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getClientsCompletedEventHandler(object sender, getClientsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getClientsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getClientsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void createClientCompletedEventHandler(object sender, createClientCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createClientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createClientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591